# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Domov
    title: Domov.
    path: homepage
  - label: Trenerji
    title: Trenerji
    path: page/trenerji
    class: first
  - label: Galerija
    title: Galerija
    path: page/galerija
  - label: Tekmovanja
    title: Tekmovanja
    path: page/tekmovanja
  - label: Rezultati
    title: Rezultati
    path: page/rezultati
  - label: Kje smo
    title: Kje smo
    path: page/kje-smo
    class: last
